# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8001d7731eb07ac77ace802635876067b45e4b007ec6f7717bfc72cb4a0baf4a2e9707fb395c0f738ddfaa0d72ebfdb313c1f03573213fe74819a26ba0851edc

test:
  secret_key_base: e2cd6e4b26ba0285e764b16d4e316fe75be6ed6cd791374ee3088b73e0c68778a746ee3d4be78336a4fb5870030d668311dbea2c93051db8f19e4697d9cc0d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
